import { stringify } from "yaml";
import { z, type ZodType } from "zod";
import {
  IdempotencyKeySchema,
  TicketIdSchema,
  TicketListQuerySchema,
  openApiComponentSchemas,
} from "./schemas.js";

type JsonObject = Record<string, unknown>;

function cleanSchema(schema: JsonObject): JsonObject {
  const clean = structuredClone(schema);
  delete clean.$schema;
  delete clean.$id;
  return clean;
}

function schemaFragment(schema: ZodType): JsonObject {
  return cleanSchema(
    JSON.parse(
      JSON.stringify(
        z.toJSONSchema(schema, {
          target: "draft-2020-12",
          io: "input",
          reused: "inline",
        }),
      ),
    ) as JsonObject,
  );
}

function componentSchemas(): Record<string, JsonObject> {
  const registry = z.registry<{ id: string }>();
  for (const [id, schema] of Object.entries(openApiComponentSchemas)) {
    registry.add(schema, { id });
  }
  const converted = z.toJSONSchema(registry, {
    target: "draft-2020-12",
    io: "input",
    uri: (id) => `#/components/schemas/${id}`,
  }) as { schemas: Record<string, JsonObject> };
  return Object.fromEntries(
    Object.entries(converted.schemas).map(([id, schema]) => [id, cleanSchema(schema)]),
  );
}

const schemaRef = (name: string) => ({ $ref: `#/components/schemas/${name}` });
const responseRef = (name: string) => ({ $ref: `#/components/responses/${name}` });
const parameterRef = (name: string) => ({ $ref: `#/components/parameters/${name}` });

const errorContent = {
  "application/json": { schema: schemaRef("ErrorResponse") },
};

export function createOpenApiDocument(): JsonObject {
  const listQueryShape = TicketListQuerySchema.shape;
  return {
    openapi: "3.1.0",
    info: {
      title: "Quanby Ticketing API",
      version: "1.0.0",
      license: { name: "MIT", identifier: "MIT" },
      description:
        "Version 1 of the connected ticketing API consumed by applications generated by `@quanby/ticketing`. All operations are scoped to the authenticated integration (`iss`) and requester (`sub`) from the bearer JWT.",
    },
    servers: [
      {
        url: "/api/v1",
        description: "Relative to the configured ticketing service origin",
      },
    ],
    security: [{ ticketingSession: [] }],
    tags: [
      {
        name: "Uploads",
        description:
          "Reserve private direct uploads before attaching them to a mutation.",
      },
      {
        name: "Tickets",
        description: "Create and read requester-scoped tickets and replies.",
      },
    ],
    paths: {
      "/uploads/presign": {
        post: {
          operationId: "presignUpload",
          summary: "Create a short-lived direct-upload URL",
          tags: ["Uploads"],
          requestBody: {
            required: true,
            content: {
              "application/json": { schema: schemaRef("PresignUploadRequest") },
            },
          },
          responses: {
            "201": {
              description: "Upload reservation created",
              content: {
                "application/json": { schema: schemaRef("PresignUploadResponse") },
              },
            },
            "400": responseRef("ValidationError"),
            "401": responseRef("UnauthorizedError"),
            "403": responseRef("ForbiddenError"),
            "413": responseRef("FileTooLargeError"),
          },
        },
      },
      "/tickets": {
        get: {
          operationId: "listTickets",
          summary: "List the authenticated requester's tickets",
          tags: ["Tickets"],
          parameters: [
            parameterRef("Cursor"),
            parameterRef("Limit"),
            parameterRef("StatusFilter"),
            parameterRef("CategoryFilter"),
          ],
          responses: {
            "200": {
              description: "A cursor-paginated ticket page",
              content: {
                "application/json": { schema: schemaRef("TicketPage") },
              },
            },
            "400": responseRef("ValidationError"),
            "401": responseRef("UnauthorizedError"),
            "403": responseRef("ForbiddenError"),
          },
        },
        post: {
          operationId: "createTicket",
          summary: "Create a ticket for the authenticated requester",
          tags: ["Tickets"],
          parameters: [parameterRef("IdempotencyKey")],
          requestBody: {
            required: true,
            content: {
              "application/json": { schema: schemaRef("CreateTicketRequest") },
            },
          },
          responses: {
            "201": {
              description: "Ticket created",
              content: {
                "application/json": { schema: schemaRef("TicketEnvelope") },
              },
            },
            "400": responseRef("ValidationError"),
            "401": responseRef("UnauthorizedError"),
            "403": responseRef("ForbiddenError"),
            "409": responseRef("IdempotencyConflictError"),
            "422": responseRef("UploadStateError"),
          },
        },
      },
      "/tickets/{ticketId}": {
        get: {
          operationId: "getTicket",
          summary: "Get one of the authenticated requester's tickets",
          tags: ["Tickets"],
          parameters: [parameterRef("TicketId")],
          responses: {
            "200": {
              description: "Ticket detail with fresh private attachment links",
              content: {
                "application/json": { schema: schemaRef("TicketEnvelope") },
              },
            },
            "401": responseRef("UnauthorizedError"),
            "403": responseRef("ForbiddenError"),
            "404": responseRef("NotFoundError"),
          },
        },
      },
      "/tickets/{ticketId}/replies": {
        post: {
          operationId: "createTicketReply",
          summary: "Reply to one of the authenticated requester's tickets",
          tags: ["Tickets"],
          parameters: [parameterRef("TicketId"), parameterRef("IdempotencyKey")],
          requestBody: {
            required: true,
            content: {
              "application/json": { schema: schemaRef("CreateReplyRequest") },
            },
          },
          responses: {
            "201": {
              description: "Reply created",
              content: {
                "application/json": { schema: schemaRef("ReplyEnvelope") },
              },
            },
            "400": responseRef("ValidationError"),
            "401": responseRef("UnauthorizedError"),
            "403": responseRef("ForbiddenError"),
            "404": responseRef("NotFoundError"),
            "409": responseRef("IdempotencyConflictError"),
            "422": responseRef("UploadStateError"),
          },
        },
      },
    },
    components: {
      securitySchemes: {
        ticketingSession: {
          type: "http",
          scheme: "bearer",
          bearerFormat: "JWT",
          description:
            "A 60-minute HS256 JWT. The protected `kid` and payload `iss` must both contain the integration client ID. The API resolves the shared secret from that ID. The audience must be `ticketing-api`.",
          "x-jwt-claims": schemaRef("TicketingClaims"),
        },
      },
      parameters: {
        TicketId: {
          name: "ticketId",
          in: "path",
          required: true,
          schema: schemaFragment(TicketIdSchema),
        },
        Cursor: {
          name: "cursor",
          in: "query",
          required: false,
          description: "Opaque cursor returned by the previous response.",
          schema: schemaFragment(listQueryShape.cursor.unwrap()),
        },
        Limit: {
          name: "limit",
          in: "query",
          required: false,
          schema: schemaFragment(listQueryShape.limit),
        },
        StatusFilter: {
          name: "status",
          in: "query",
          required: false,
          schema: schemaRef("TicketStatus"),
        },
        CategoryFilter: {
          name: "category",
          in: "query",
          required: false,
          schema: schemaRef("TicketCategory"),
        },
        IdempotencyKey: {
          name: "Idempotency-Key",
          in: "header",
          required: true,
          description:
            "Unique key for this mutation. Repeating a request with the same key and body returns the original result; reusing it with a different body returns `IDEMPOTENCY_CONFLICT`.",
          schema: schemaFragment(IdempotencyKeySchema),
        },
      },
      responses: {
        ValidationError: {
          description: "Request validation failed",
          content: {
            ...errorContent,
            "application/json": {
              schema: schemaRef("ErrorResponse"),
              examples: {
                validation: {
                  value: {
                    error: {
                      code: "VALIDATION_ERROR",
                      message: "The request is invalid.",
                      fieldErrors: {
                        title: ["Title must contain at least 3 characters."],
                      },
                    },
                  },
                },
              },
            },
          },
        },
        UnauthorizedError: {
          description: "Session is missing, invalid, or expired",
          content: errorContent,
        },
        ForbiddenError: {
          description: "The session does not include the required scope",
          content: errorContent,
        },
        NotFoundError: {
          description: "Resource not found for this requester",
          content: errorContent,
        },
        IdempotencyConflictError: {
          description: "The idempotency key was reused with a different request",
          content: errorContent,
        },
        UploadStateError: {
          description:
            "An upload is missing, incomplete, already attached, or belongs to another requester",
          content: errorContent,
        },
        FileTooLargeError: {
          description: "The requested upload exceeds the server limit",
          content: errorContent,
        },
      },
      schemas: componentSchemas(),
    },
  };
}

export function renderOpenApiDocument(): string {
  return stringify(createOpenApiDocument(), {
    indent: 2,
    lineWidth: 100,
    defaultKeyType: "PLAIN",
    defaultStringType: "PLAIN",
  });
}
